version: "3.8"

services:
  user-service:
    build:
      context: ./microservices-app/user-service
    ports:
      - "3000:3000"
    networks:
      - app-network

  product-service:
    build:
      context: ./microservices-app/product-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  order-service:
    build:
      context: ./microservices-app/order-service
    ports:
      - "3002:3002"
    networks:
      - app-network

  gateway-service:
    build:
      context: ./microservices-app/gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
